#!/bin/bash
GREEN='\033[0;32m########'
NC='########\033[0m' # No Color

echo -e ${GREEN}Installing Domoserv_pi${NC}

echo -e ${GREEN}Installing qt5${NC}
sudo apt-get install qt5-default libqt5websockets5-dev libqt5sql5-sqlite -y

mkdir lib
mkdir dep
cd dep

echo -e ${GREEN}Cloning WiringPi${NC}
git clone https://github.com/WiringPi/WiringPi.git

echo -e ${GREEN}Cloning CryptoFire${NC}
git clone https://github.com/firedream89/CryptoFire.git

echo -e ${GREEN}Cloning ServerFire${NC}
git clone https://github.com/firedream89/ServerFire.git

echo -e ${GREEN}Compiling WiringPi${NC}
cd WiringPi
sudo ./build
cd ..

echo -e ${GREEN}Compiling CryptoFire${NC}
cd ../lib
qmake ../dep/CryptoFire/src/
make

echo -e ${GREEN}Compiling ServerFire${NC}
qmake ../dep/ServerFire/src/
make

echo -e ${GREEN}Updating librarys path${NC}
sudo cp -r ../lib /usr/local/
echo /usr/local/lib | sudo tee /etc/ld.so.conf.d/lib.conf
sudo ldconfig

echo -e ${GREEN}Compiling Domoserv_pi${NC}
cd ../build
qmake ../domoserv_pi/
make
mv domoserv_pi2 domoserv_pi
cd ..

# creating deamon
echo -e ${GREEN}install deamon${NC}
sudo cp domoserv_pi.service /lib/systemd/system/domoserv_pi.service
sudo chmod 644 /lib/systemd/system/domoserv_pi.service
chmod +x /home/pi/domoserv_pi/domoserv_pi
sudo systemctl daemon-reload
sudo systemctl enable domoserv_pi.service
sudo systemctl start domoserv_pi.service

# Reboot
echo -e ${GREEN}rebooting${NC}
sudo reboot
